#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-h3xsteram-retirejs
Version  : 3.0.1
Release  : 2
URL      : https://github.com/RetireJS/retire.js/tarball/master
Source0  : https://github.com/RetireJS/retire.js/tarball/master
Source1  : https://repo1.maven.org/maven2/com/h3xstream/retirejs/retirejs-core/3.0.1/retirejs-core-3.0.1.jar
Source2  : https://repo1.maven.org/maven2/com/h3xstream/retirejs/retirejs-core/3.0.1/retirejs-core-3.0.1.pom
Source3  : https://repo1.maven.org/maven2/com/h3xstream/retirejs/retirejs-root-pom/3.0.1/retirejs-root-pom-3.0.1.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: mvn-h3xsteram-retirejs-data = %{version}-%{release}
Requires: mvn-h3xsteram-retirejs-license = %{version}-%{release}

%description
Retire.js
=========
[![Retire Status](http://retire.insecurity.today/api/image?uri=https://raw.githubusercontent.com/RetireJS/retire.js/master/node/package.json)](http://retire.insecurity.today/api/image?uri=https://raw.githubusercontent.com/RetireJS/retire.js/master/node/package.json)

%package data
Summary: data components for the mvn-h3xsteram-retirejs package.
Group: Data

%description data
data components for the mvn-h3xsteram-retirejs package.


%package license
Summary: license components for the mvn-h3xsteram-retirejs package.
Group: Default

%description license
license components for the mvn-h3xsteram-retirejs package.


%prep
%setup -q -n RetireJS-retire.js-9b6a4f7

%build

%install
mkdir -p %{buildroot}/usr/share/package-licenses/mvn-h3xsteram-retirejs
cp LICENSE.md %{buildroot}/usr/share/package-licenses/mvn-h3xsteram-retirejs/LICENSE.md
mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/h3xstream/retirejs/retirejs-core/3.0.1
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/com/h3xstream/retirejs/retirejs-core/3.0.1/retirejs-core-3.0.1.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/h3xstream/retirejs/retirejs-core/3.0.1
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/com/h3xstream/retirejs/retirejs-core/3.0.1/retirejs-core-3.0.1.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/h3xstream/retirejs/retirejs-root-pom/3.0.1
cp %{SOURCE3} %{buildroot}/usr/share/java/.m2/repository/com/h3xstream/retirejs/retirejs-root-pom/3.0.1/retirejs-root-pom-3.0.1.pom


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/com/h3xstream/retirejs/retirejs-core/3.0.1/retirejs-core-3.0.1.jar
/usr/share/java/.m2/repository/com/h3xstream/retirejs/retirejs-core/3.0.1/retirejs-core-3.0.1.pom
/usr/share/java/.m2/repository/com/h3xstream/retirejs/retirejs-root-pom/3.0.1/retirejs-root-pom-3.0.1.pom

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/mvn-h3xsteram-retirejs/LICENSE.md
